### ISSUE TITLE
Bug in patternProperties

### ISSUE THREAD

**Issue by CuthbertJungle** [mafintosh/is-my-json-valid#56]
the json should be failed by the schema as 'a' does not match the patternProperties regex. However the json is accepted and no errors are returned

schema:

{
    "type": "object",
    "properties": {
        "fixedKey": {
            "type": "object",
            "patternProperties": {
                "[0-9]*": {}
            },
            "additionalProperties": false
        }
    }
}

test json:

{
    "fixedKey": {
        "1": {},
        "a": {}
    }
}

**Comment by chrahunt** [comment]
By default, a regular expression in JSON Schema passes if it matches anywhere in the property string in question. Since the regex `[0-9]*` matches an empty string and the empty string is a substring of all strings, it will end up matching all properties. Take a look at the explanation under the example in the "Base Schema" section [here](http://json-schema.org/example2.html).

For your specific example, "anchoring" the regular expression with `^` and `$` at the beginning and end enforces the requirement that "this regular expression must match the whole property identifier". This example gives the expected result:

```javascript
var validator = require('is-my-json-valid');

var validate = validator({
  "type": "object",
  "properties": {
    "fixedKey": {
      "type": "object",
      "patternProperties": {
        "^[0-9]+$": {}
      },
      "additionalProperties": false
    }
  }
});

console.log(validate({
  "fixedKey": {
    "1": {},
    "a": {}
  }
})); // false
```

In case this aligned pretty closely with the code you were trying to write and could help, I also substituted the `*` in your regex with `+`. `+` says to match "at least one" of the preceding character. This way, properties must have at least one number in them, which is usually the desired behavior.
