### ISSUE TITLE
error codes & localization

### ISSUE THREAD

**Issue by shachr** [mafintosh/is-my-json-valid#80]
Please add support for error codes, this will allow better understanding of the errors, and allow us as developers to localize the error messages,
currently errors contains:
1. field
2. value
3. message

we also need:
1. errorCode 

this means that its should be supported in the custom format as well,

Thanks,

**Comment by yoshuawuyts** [comment]
You can wrap the `Error`s produced by this package using the [error](https://github.com/Raynos/error) package. I don't see the point of having per-field errorCode as `message` is easy to string match and override if necessary. Closing because this issue is slightly stale, happy to reopen if it's needed to discuss this further.
